# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnschuh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='transferfile',
            name='direction',
            field=models.BooleanField(choices=[(True, 'Upload'), (False, 'Download')]),
        ),
        migrations.AlterField(
            model_name='transferfile',
            name='fileType',
            field=models.IntegerField(choices=[(0, 'TaskData'), (1, 'Documents')], default=0),
        ),
        migrations.AlterField(
            model_name='transferfile',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
