# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnschuh', '0002_auto_20191016_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferfile',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
