# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnschuh', '0004_remove_transferfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfile',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
