# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnschuh', '0005_transferfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferfile',
            name='name',
        ),
    ]
